#!/usr/bin/env python3
import argparse
import os
import sys

def main(args):
    file = open(args.file, 'r') if args.file else sys.stdin

    contents = file.read()

    file_bytes = len(contents.encode('utf-8'))
    file_lines = contents.count('\n')
    file_words = len(contents.split())

    if not any([args.c, args.l, args.w, args.m]):
        print(file_bytes, file_lines, file_words, args.file if args.file else '')
    if args.c:
        print(file_bytes, args.file if args.file else '')
    if args.l:
        print(file_lines, args.file if args.file else '')
    if args.w:
        print(file_words, args.file if args.file else '')
    if args.m:
        file_chars = len(contents.encode('utf-8').decode('utf-8', 'ignore'))
        print(file_chars, args.file if args.file else '')

    if args.file:
        file.close()

    return 0

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="wc tool in python")
    parser.add_argument('-c', action='store_true', help='Output the number of bytes in the file')
    parser.add_argument('-l', action='store_true', help='Output the number of lines in the file')
    parser.add_argument('-w', action='store_true', help='Output the number of words in the file')
    parser.add_argument('-m', action='store_true', help='Output the number of characters in the file')
    parser.add_argument('file', type=str, nargs='?', help='The file to count')
    args = parser.parse_args()
    main(args)